# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
          cache: "npm"
      - run: npm ci
      - run: npm run check --if-present
      - run: npm run build --if-present
      - run: npm run package --if-present
      - run: npm run test --if-present
